apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bankapp-pvc
  namespace: bankapp-namespace
  labels:
    app: bankapp
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard  # Matches the PV's storageClassName
  volumeName: bankapp-pv
