apiVersion: v1
kind: PersistentVolume
metadata:
  name: bankapp-pv
  namespace: bankapp-namespace
  labels:
    app: bankapp
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain  # Keeps the PV after the PVC is deleted
  storageClassName: standard  # Make sure this matches your cluster's default storage class
  hostPath:
    path: /tmp/bankapp-mysql
    type: DirectoryOrCreate
